# Generated by Django 5.2.14 on 2026-05-12 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('kasallik_nomi', models.CharField(blank=True, max_length=255)),
                ('ishonch_darajasi', models.CharField(blank=True, choices=[('yuqori', 'Yuqori'), ('orta', "O'rta"), ('past', 'Past')], max_length=10)),
                ('sababi', models.TextField(blank=True)),
                ('belgilari', models.JSONField(default=list)),
                ('davolash', models.JSONField(default=list)),
                ('oldini_olish', models.JSONField(default=list)),
                ('shoshilinchlik', models.CharField(blank=True, choices=[('yuqori', 'Yuqori'), ('orta', "O'rta"), ('past', 'Past')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
